2025-03-06 22:43:04,620 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.130.49.36:43141'
2025-03-06 22:43:04,621 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.130.49.36:34245'
2025-03-06 22:43:06,600 - distributed.worker - INFO -       Start worker at:   tcp://10.130.49.36:35795
2025-03-06 22:43:06,601 - distributed.worker - INFO -       Start worker at:   tcp://10.130.49.36:39311
2025-03-06 22:43:06,601 - distributed.worker - INFO -          Listening to:   tcp://10.130.49.36:35795
2025-03-06 22:43:06,601 - distributed.worker - INFO -           Worker name:             SLURMCluster-1
2025-03-06 22:43:06,601 - distributed.worker - INFO -          Listening to:   tcp://10.130.49.36:39311
2025-03-06 22:43:06,601 - distributed.worker - INFO -          dashboard at:         10.130.49.36:35989
2025-03-06 22:43:06,601 - distributed.worker - INFO -           Worker name:             SLURMCluster-0
2025-03-06 22:43:06,601 - distributed.worker - INFO - Waiting to connect to:  tcp://10.130.56.192:39603
2025-03-06 22:43:06,601 - distributed.worker - INFO -          dashboard at:         10.130.49.36:41353
2025-03-06 22:43:06,601 - distributed.worker - INFO - -------------------------------------------------
2025-03-06 22:43:06,601 - distributed.worker - INFO - Waiting to connect to:  tcp://10.130.56.192:39603
2025-03-06 22:43:06,601 - distributed.worker - INFO -               Threads:                          5
2025-03-06 22:43:06,601 - distributed.worker - INFO - -------------------------------------------------
2025-03-06 22:43:06,601 - distributed.worker - INFO -                Memory:                 488.28 MiB
2025-03-06 22:43:06,601 - distributed.worker - INFO -               Threads:                          5
2025-03-06 22:43:06,601 - distributed.worker - INFO -       Local Directory: /tmp/tmp-g88077/dask-scratch-space/worker-eeektmf1
2025-03-06 22:43:06,601 - distributed.worker - INFO -                Memory:                 488.28 MiB
2025-03-06 22:43:06,601 - distributed.worker - INFO - -------------------------------------------------
2025-03-06 22:43:06,601 - distributed.worker - INFO -       Local Directory: /tmp/tmp-g88077/dask-scratch-space/worker-dq_rw20i
2025-03-06 22:43:06,601 - distributed.worker - INFO - -------------------------------------------------
2025-03-06 22:43:08,698 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-03-06 22:43:08,699 - distributed.worker - INFO -         Registered to:  tcp://10.130.56.192:39603
2025-03-06 22:43:08,699 - distributed.worker - INFO - -------------------------------------------------
2025-03-06 22:43:08,699 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-03-06 22:43:08,700 - distributed.core - INFO - Starting established connection to tcp://10.130.56.192:39603
2025-03-06 22:43:08,700 - distributed.worker - INFO -         Registered to:  tcp://10.130.56.192:39603
2025-03-06 22:43:08,700 - distributed.worker - INFO - -------------------------------------------------
2025-03-06 22:43:08,701 - distributed.core - INFO - Starting established connection to tcp://10.130.56.192:39603
slurmstepd: error: *** JOB 51519653 ON crcn0266 CANCELLED AT 2025-03-06T22:43:12 ***
2025-03-06 22:43:12,316 - distributed.worker - INFO - Stopping worker at tcp://10.130.49.36:39311. Reason: scheduler-close
2025-03-06 22:43:12,316 - distributed.worker - INFO - Stopping worker at tcp://10.130.49.36:35795. Reason: scheduler-close
slurmstepd: error: *** JOB 51519652 ON crcn0266 CANCELLED AT 2025-03-06T22:43:12 ***
2025-03-06 22:43:12,317 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.130.49.36:35334 remote=tcp://10.130.56.192:39603>
Traceback (most recent call last):
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
             ^^^^^^^^^^
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.130.49.36:35334 remote=tcp://10.130.56.192:39603>: Stream is closed
2025-03-06 22:43:12,317 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.130.49.36:35340 remote=tcp://10.130.56.192:39603>
Traceback (most recent call last):
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
             ^^^^^^^^^^
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.130.49.36:35340 remote=tcp://10.130.56.192:39603>: Stream is closed
2025-03-06 22:43:12,321 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.130.49.36:43141'. Reason: scheduler-close
2025-03-06 22:43:12,321 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.130.49.36:34245'. Reason: scheduler-close
2025-03-06 22:43:12,323 - distributed.core - INFO - Received 'close-stream' from tcp://10.130.56.192:39603; closing.
2025-03-06 22:43:12,323 - distributed.core - INFO - Received 'close-stream' from tcp://10.130.56.192:39603; closing.
2025-03-06 22:43:12,323 - distributed.nanny - INFO - Worker closed
2025-03-06 22:43:12,323 - distributed.nanny - INFO - Worker closed
